name: Appium CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ui-tests:
    strategy:
      matrix:
        include:
          - xcodeVersion: 13.1
            deviceName: iPhone X
            iosVersion: 15.0
          - xcodeVersion: 14.2
            deviceName: iPhone 14
            iosVersion: 16.2
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3.6.0
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'gradle'
    - name: Install the Emulator
      run: |
        chmod +x ./scripts/RunAppiumServer.sh
        ./scripts/RunAppiumServer.sh
      shell: bash   
    - name: List iOS Devices & Platforms
      run: |
          xcrun simctl list
    - name: Install iOS 11.4 Runtime
      run: |
          gem install xcode-install
          xcversion simulators --install='iOS 11.4'
    - name: Create and Run iOS Emulator - iPhoneX on iOS 11.4, Update default appium config for iOS
      run: |
        xcrun simctl create TestiPhoneX com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-11-4 > deviceid.txt 
        DEVICEUUID=`cat deviceid.txt`          
        echo $DEVICEUUID          
        sed -i -e "s/{IPHONE_UUID}/$DEVICEUUID/g" __tests__/e2e/template_appium_configs_ios.js          
        xcrun simctl boot $DEVICEUUID &
    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: unit_test_report
        path: /Users/runner/work/-appiumExample/  
        
